### ISSUE TITLE
~ and ` can't be typed alone

### ISSUE THREAD

**Issue by GuimLe** [hwtnb/SylphyHornPlusWin11#8]
Hi there,
You have done great work on this app, just what I need. I found a bug when I'm trying to type a single back tick ``` ` ``` and tilde `~`.
I'm using french keyboard and I usually use this combination of keys : <kbd>Alt Gr</kbd> + <kbd>7</kbd>, release all keys and then press <kbd>space</kbd>. Same thing happen when I'm trying to replace <kbd>7</kbd> by <kbd>2</kbd> to produce a single `~`.
When I type multiples one, it works, it seems there is a problem with the space bar after <kbd>Alt Gr</kbd> + <kbd>7</kbd>.
If the app is not running, there is no problem at all.

**Comment by hwtnb** [comment]
@GuimLe Thanks for your report.
Unfortunately, I had been working for a while and could not reproduce the issue.

I don't have a French keyboard and just set the system language to French. In such a situation, I could not see any difference, at least in my environment, with or without the app running.

It seems to be a bug in the library if it exists. Maybe it is related to the issue lontivero/Open.WinKeyboardHook#5, but I am not sure.

**Comment by GuimLe** [comment]
Hi and thank you for your answer.
I think you're right, it could be related to this issue but the maintainer doesn't seem to merge PR since 2019.
There is a [fork](https://github.com/etrange02/Open.WinKeyboardHook) of it which seem to address this bug, but I'm really not sure of it.

**Comment by hwtnb** [comment]
@GuimLe I built a test binary that includes a fork of the library. 
[SylphyHornPlus-Ver4.0.0-beta.6-keyhookTest.zip](https://github.com/hwtnb/SylphyHornPlusWin11/files/9717420/SylphyHornPlus-Ver4.0.0-beta.6-keyhookTest.zip)

I had to fix the fork project a bit to work on SylphyHornPlus, so I am not sure the bug is fixed.

**Comment by GuimLe** [comment]
Thank you for this implementation, I've tested it but, nothing has changed, ``~`^¨`` keys are still ignored.
It seems that this fork doesn't resolve any bug.
I'm sorry for this waste of time

**Comment by gitthangbaby** [comment]
I've tried it too, but this andf new version also disables all diacritics globally, dozens of combinations with Alt = combination.
